version: '3'
services:
  postgres14-02:
    restart: unless-stopped
    image: postgres:14
    container_name: postgres14-02
    ports:
        - 5432:5432
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
    volumes:
      - type: bind
        source: /zfs_master/docker/data/postgres14
        target: /var/lib/postgresql/data
      - type: bind
        source: /glusterfs/vols/share
        target: /glusterfs/share
        read_only: true
    networks:
      vlan10:
        ipv4_address: "192.168.10.44"
        
#  mssql2019:
#    restart: unless-stopped
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    container_name: mssql2019
#    ports:
#        - 1433:1433
#    environment:
#        - ACCEPT_EULA=Y
#        - SA_PASSWORD=${MSSQL_PASSWORD:?err}
#    volumes:
#      - type: bind
#        source: /zfs_master/docker/data/mssql2019
#        target: /var/opt/mssql/data
#      - type: bind
#        source: /glusterfs/vols/share
#        target: /glusterfs/share
#        read_only: true
#    networks:
#      vlan10:
#        ipv4_address: "192.168.10.84"

  pghero:
    image: ankane/pghero
    restart: always
    ports:
      - "8080:8080"
    environment:
      PGHERO_DB_URL: postgres://{username}:{passowrd}@192.168.10.43:5432
    volumes:
      - type: bind
        source: /zfs_master/docker/data/pghero/pghero.yml
        target: /app/config/pghero.yml
    networks:
      vlan10:
        ipv4_address: "192.168.10.91"

networks:
  vlan10:
    external: true
