version: '2.2'
services:
  es56x1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    restart: unless-stopped
    container_name: es56x1
    environment:
      - node.name=es56x1
      - cluster.name=${ES_CLUSTER_NAME:?err}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      vlan10:
        ipv4_address: 192.168.10.87
  es56x22:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    restart: unless-stopped
    container_name: es56x2
    environment:
      - node.name=es56x2
      - cluster.name=${ES_CLUSTER_NAME:?err}
      - discovery.zen.ping.unicast.hosts=es56x1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      vlan10:
        ipv4_address: 192.168.10.88

networks:
  vlan10:
    external: true
