version: '2.4'
services:
  haproxy-01:
    image: haproxy:latest
    container_name: haproxy-01
    restart: unless-stopped
    user: root
    ports:
      - 443:443
      - 80:80
      - 9000:9000
      - 6443:6443
      - 22623:22623
    volumes:
      - type: bind
        source: /glusterfs/vols/haproxy/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true
      - type: bind
        source: /glusterfs/vols/haproxy/certs
        target: /usr/local/etc/haproxy/certs
        read_only: true
    networks:
      vlan10:
        ipv4_address: 192.168.10.40
        
networks:
  vlan10:
    name: vlan10
    driver: macvlan
    driver_opts:
      parent: bridge10
    ipam:
      config:
        - subnet: "192.168.10.0/24"
          ip_range: "192.168.10.1/24"
          gateway: "192.168.10.1"
